version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_stealth
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - github.com/muasx88/stealth_commerce

volumes:
  postgres_data:

networks:
  github.com/muasx88/stealth_commerce:
    driver: bridge
